### ISSUE TITLE
Black bubble in Mars.1 Release (4.5.1) on Ubuntu

### ISSUE THREAD

**Issue by brokenjpl** [stoupa91/eclipse-xpath-evaluation-plugin#6]
This black bubble appears everytime I hit enter in the X-path field.

![screenshot from 2016-02-11 09 35 30](https://cloud.githubusercontent.com/assets/17048935/12979146/4df0c794-d0a3-11e5-965a-5e7d226c0529.png)

**Comment by stoupa91** [comment]
This is not the problem of the plugin. This issue is related to eclipse and how it gets the system settings for displaying tooltips. Many people seem to have the very same issue with these "black tooltips" in different versions of eclipse. The only working solution I was able to find was to add following two lines into eclipse.ini file:

--launcher.GTK_version
2
